src/Entity/Project.php
<?php

namespace App\Entity;

class Project implements \JsonSerializable
{
    use JsonDeserializable;

    public function __construct(
        public string $id,
        public string $title,
        public string $date,
        public string $shortDesc,
        public array $tags,
        public ?string $link = null,
        public ?string $clientName = null,
        public ?string $clientLink = null,
        public ?string $context = null,
    ){
    }

    public function getTags(): array
    {
        return array_map(fn($tag) => mb_strtolower($tag), $this->tags);
    }

    public function getTagsAsKeys(): array
    {
        return array_fill_keys(array_map(fn($tag) => mb_strtolower($tag), $this->tags), null);
    }
}

templates/page/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block main %}
    <twig:BreadcrumbGroup>
        <twig:BreadcrumbItem href="{{ path('app_articles') }}">
            Articles
        </twig:BreadcrumbItem>
    </twig:BreadcrumbGroup>
    <twig:Title level="1">
        {{ article.title }}
        <small class="text-sm text-gray-500">{{ article.date|date('Y-m-d') }}</small>
    </twig:Title>

    <div class="article">
        <img class="lg:float-right lg:max-w-[50%] lg:ml-4 lg:mb-2 rounded-t-lg md:rounded-none md:rounded-s-lg" src="{{ asset('images/article/'~article.slug~'.jpg') }}" alt="" />
        {{ article.content|raw }}
    </div>
{% endblock %}

templates/page/article_create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create article{% endblock %}

{% block main %}
    <twig:BreadcrumbGroup>
        <twig:BreadcrumbItem href="{{ path('app_articles') }}">
            Projets
        </twig:BreadcrumbItem>
    </twig:BreadcrumbGroup>
    <twig:Title level="1">
        Create article
    </twig:Title>
    <div class="flex gap-4 flex-col md:flex-row">
            <div class="">
            {{ form_start(form) }}
                {{ form_rest(form) }}
                <twig:Button submit="true">Enregistrer</twig:Button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/page/article_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit {{ article.title }}{% endblock %}

{% block main %}
    <twig:BreadcrumbGroup>
        <twig:BreadcrumbItem href="{{ path('app_articles') }}">
            Projets
        </twig:BreadcrumbItem>
    </twig:BreadcrumbGroup>
    <twig:Title level="1">
        {{ article.title }}
        <small class="text-sm text-gray-500">{{ article.date|date('Y-m-d') }}</small>
    </twig:Title>
    <div class="flex gap-4 flex-col md:flex-row">
            <div class="">
            {{ form_start(form) }}
                {{ form_rest(form) }}
                <twig:Button submit="true">Enregistrer</twig:Button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/page/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block main %}
    <twig:GridArticles />
{% endblock %}

templates/page/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block main %}
    <div class="flex flex-col md:flex-row w-full gap-8 mt-12">
        <article class="grow">
            <twig:Title>
                Envoyez-moi un message
            </twig:Title>
            {% include 'layouts/partials/form_hire.html.twig' %}
            {% if contact|default(false) %}
                {% block success_stream %}
                    <turbo-stream action="replace" targets="[data-id=form_hire_footer]">
                        <template>
                            <twig:Alert>
                                Merci {{ contact.name }}. Votre message a bien été envoyé.
                                <twig:block name="title">
                                    Succès !
                                </twig:block>
                            </twig:Alert>
                        </template>
                    </turbo-stream>
                {% endblock %}
            {% endif %}
        </article>
        <article class="grow">
            <twig:Title class="sr-only">
                Autres infos de contact
            </twig:Title>
            <twig:DefGroup>
                <twig:DefItem title="Identité">
                    Vincent Beauvivre
                </twig:DefItem>
                <twig:DefItem title="Localisation">
                    Nantes, France
                </twig:DefItem>
                <twig:DefItem title="Modalité">
                    Distanciel ou présentiel
                </twig:DefItem>
                <twig:DefItem title="Mobilité">
                    <ul>
                        <li>Courte période : France entière</li>
                        <li>Longue période : Loire-Atlantique</li>
                    </ul>
                </twig:DefItem>
                <twig:DefItem title="Statuts possibles">
                    Employeriat, Contrat freelance
                </twig:DefItem>
                <twig:DefItem title="Siret">
                    938400256
                </twig:DefItem>
            </twig:DefGroup>
        </article>
    </div>

{% endblock %}

templates/page/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Développeur web{% endblock %}

{% block main %}
    {% include 'layouts/partials/hero.html.twig' %}
    {% include 'layouts/partials/projects.html.twig' %}
    {% include 'layouts/partials/articles.html.twig' %}
{% endblock %}

templates/page/project.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.title }}{% endblock %}

{% block main %}
    <twig:BreadcrumbGroup>
        <twig:BreadcrumbItem href="{{ path('app_projects') }}">
            Projets
        </twig:BreadcrumbItem>
    </twig:BreadcrumbGroup>
    <twig:Title level="1">
        {{ project.title }}
        <small class="text-sm text-gray-500">{{ project.date }}</small>
    </twig:Title>
    <div class="flex gap-4 flex-col md:flex-row">
        <div class="rounded-xl bg-black overflow-hidden p-2 ">
            <div class="rounded-md border border-4 border-indigo-500 overflow-hidden">
                <img src="{{ asset('images/project/'~project.id~'.png') }}"
                     alt="Projet web {{ project.title }}"
                     class="aspect-[780/680]"
                />
            </div>
        </div>
        <div class="">
            <twig:DefGroup>
                <twig:DefItem title="Date">
                    {{ project.date }}
                </twig:DefItem>
                <twig:DefItem title="Description">
                    {{ project.shortDesc }}
                </twig:DefItem>
                <twig:DefItem title="Tags">
                    <div class="flex gap-2 flex-wrap">
                        {% for tag, count in project.tagsAsKeys %}
                            <a href="{{ path('app_projects', {tags: [tag]}) }}" class="text-sm font-medium py-0.5 px-2.5 rounded-full cursor-pointer border border-2 relative
                                hover:bg-amber-200 hover:dark:bg-amber-600"
                                   style="border-color: #{{ tag|stringToColor }}; "
                            >
                                {{ tag|title }}
                            </a>
                        {% endfor %}
                    </div>
                </twig:DefItem>
                {% if project.clientName %}
                    <twig:DefItem title="Client">
                        <twig:Link href="{{ project.clientLink }}">
                            {{ project.clientName }}
                        </twig:Link>
                    </twig:DefItem>
                {% endif %}
                {% if project.context %}
                    <twig:DefItem title="Contexte" class="article">
                        {{ project.context|raw }}
                    </twig:DefItem>
                {% endif %}
            </twig:DefGroup>
            {% if project.link %}
                <twig:Button href="{{ project.link }}" target="_blank">
                    Voir le projet
                </twig:Button>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/page/project_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit {{ project.title }}{% endblock %}

{% block main %}
    <twig:BreadcrumbGroup>
        <twig:BreadcrumbItem href="{{ path('app_projects') }}">
            Projets
        </twig:BreadcrumbItem>
    </twig:BreadcrumbGroup>
    <twig:Title level="1">
        {{ project.title }}
        <small class="text-sm text-gray-500">{{ project.date }}</small>
    </twig:Title>
    <div class="flex gap-4 flex-col md:flex-row">
            <div class="">
            {{ form_start(form) }}
                {{ form_rest(form) }}
                <twig:Button submit="true">Enregistrer</twig:Button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/page/projects.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets{% endblock %}

{% block main %}
    <twig:GridProjects />
{% endblock %}